# Generated by Django 5.0.4 on 2024-04-24 06:56

import sortedm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='employee',
        ),
        migrations.AddField(
            model_name='stock',
            name='employers',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='core.employee', verbose_name='Сотрудники'),
        ),
    ]
