# Generated by Django 5.0.4 on 2024-04-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_stock_employee_stock_employers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_size',
            field=models.CharField(choices=[('выдан', 'выдан'), ('не выдан', 'не выдан')], default='большой заказ', max_length=30, verbose_name='Размер заказа'),
        ),
    ]
