# Generated by Django 5.0.4 on 2024-04-24 08:36

import sortedm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cell_free_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='orders',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, null=True, to='core.order', verbose_name='Заказы'),
        ),
    ]
