# Generated by Django 5.0.4 on 2024-04-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cell_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='telegram_id'),
        ),
    ]
