# Generated by Django 5.0.1 on 2024-04-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='Оценка'),
        ),
    ]
