# Generated by Django 5.0.1 on 2024-04-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='at_the_pick_up_point',
            field=models.BooleanField(default=False, verbose_name='На пункте выдачи'),
        ),
    ]
